### ISSUE TITLE
Move 1 minute wait to loopback side of cycle

### ISSUE THREAD

**Issue by ben-w1** [awslabs/aws-sdlc-controltower-extension#4]
Currently the step function will always execute the wait for one minute step. Moving this step to the loopback side of the cycle would allow for the sfn to check if account creation is complete before automatically waiting for one minute. 

Would it be feasible to move this step to the end of the loopback cycle?

**Comment by sjohnsam** [comment]
proposed new step function diagram:
![stepfunction-diagramv2](https://user-images.githubusercontent.com/36959356/120544841-dbde1f00-c3bb-11eb-936b-93b706e9a88a.png)

**Comment by JustinKuskowski** [comment]
Closing from PR https://github.com/awslabs/aws-sdlc-controltower-extension/pull/7
