### ISSUE TITLE
account creation fails due to timeout

### ISSUE THREAD

**Issue by dconry-torc** [awslabs/aws-sdlc-controltower-extension#5]
Often, account creations fail after exactly 1 hour.  A terminate & rerun with same parameters appears to succeed in some cases.  

Associated error message:
CloudFormation did not receive a response from your Custom Resource. Please check your logs for requestId [snipped]. If you are using the Python cfn-response module, you may need to update your Lambda function code so that CloudFormation can attach the updated version.

Still trying to collect more data about these fails & will update this issue.

**Comment by dconry-torc** [comment]
We discovered the input to this function contained an OutputKey ("SSOUserPortal") with no corresponding OutputValue.  It seemed  prudent to handle the general case of missing value (and this solution allowed acct creation to proceed), but might be there is a better way to fix.

**Comment by dconry-torc** [comment]
Further info as per contrib guidelines:
1. Using main branch
2. Input example: {"OutputKey":"SSOUserName","OutputValue":"Some Guy",...,"OutputKey":"SSOUserPortal","Description":"blabla"}
3. Possible this could be environment specific.

**Comment by JustinKuskowski** [comment]
https://github.com/awslabs/aws-sdlc-controltower-extension/pull/6 had been merged and this should no longer be an issue.
